package pojo;
// Generated Oct 5, 2021 9:26:00 AM by Hibernate Tools 4.3.1



/**
 * TblFurniture generated by hbm2java
 */
public class TblFurniture  implements java.io.Serializable {


     private String idFurniture;
     private String nama;
     private String diskripsi;
     private String harga;
     private String stok;

    public TblFurniture() {
    }

    public TblFurniture(String idFurniture, String nama, String diskripsi, String harga, String stok) {
       this.idFurniture = idFurniture;
       this.nama = nama;
       this.diskripsi = diskripsi;
       this.harga = harga;
       this.stok = stok;
    }
   
    public String getIdFurniture() {
        return this.idFurniture;
    }
    
    public void setIdFurniture(String idFurniture) {
        this.idFurniture = idFurniture;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getDiskripsi() {
        return this.diskripsi;
    }
    
    public void setDiskripsi(String diskripsi) {
        this.diskripsi = diskripsi;
    }
    public String getHarga() {
        return this.harga;
    }
    
    public void setHarga(String harga) {
        this.harga = harga;
    }
    public String getStok() {
        return this.stok;
    }
    
    public void setStok(String stok) {
        this.stok = stok;
    }




}


