package pojo;
// Generated Oct 5, 2021 9:26:00 AM by Hibernate Tools 4.3.1



/**
 * TblPelanggan generated by hbm2java
 */
public class TblPelanggan  implements java.io.Serializable {


     private String idPelanggan;
     private String nama;
     private String alamat;
     private String noTelp;
     private String email;

    public TblPelanggan() {
    }

    public TblPelanggan(String idPelanggan, String nama, String alamat, String noTelp, String email) {
       this.idPelanggan = idPelanggan;
       this.nama = nama;
       this.alamat = alamat;
       this.noTelp = noTelp;
       this.email = email;
    }
   
    public String getIdPelanggan() {
        return this.idPelanggan;
    }
    
    public void setIdPelanggan(String idPelanggan) {
        this.idPelanggan = idPelanggan;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


